### ISSUE TITLE
Multiple stores

### ISSUE THREAD

**Issue by pe3** [netgusto/IdiomaticReact#6]
Hi. Nice initiative.

It might be good to use several stores in the app. Most React examples only deal with one. Multiple stores would also help in explaining the need for a dispatcher.

Take a look at the [flux-chat example](https://github.com/facebook/flux/tree/master/examples/flux-chat/js) and the [presentation explaining it](http://facebook.github.io/flux/docs/chat.html#content).

**Comment by prabirshrestha** [comment]
+1 Also would like to see how `waitFor` would be implemented.

**Comment by netgusto** [comment]
Done. Check it out on branch `chat` !

**Comment by netgusto** [comment]
@prabirshrestha @pe3 if you feel like reviewing :)

**Comment by prabirshrestha** [comment]
@netgusto just glanced through it. It looks good. For some reason I would still prefer `waitFor` instead of `wait` for the name.
